Configurations pertinent to topics have both a global default as well an optional per-topic override.
If no per-topic configuration is given the global default is used.
The override can be set at topic creation time by giving one or more =--config= options.
This example creates a topic named /my-topic/ with a custom max message size and flush rate:

#+BEGIN_SRC
 > bin/kafka-topics.sh --zookeeper localhost:2181 --create --topic my-topic --partitions 1
        --replication-factor 1 --config max.message.bytes=64000 --config flush.messages=1
#+END_SRC

Overrides can also be changed or set later using the alter topic command. This example updates the max message size for /my-topic/:

#+BEGIN_SRC
 > bin/kafka-topics.sh --zookeeper localhost:2181 --alter --topic my-topic
    --config max.message.bytes=128000
#+END_SRC

To remove an override you can do

#+BEGIN_SRC
 > bin/kafka-topics.sh --zookeeper localhost:2181 --alter --topic my-topic
    --deleteConfig max.message.bytes
#+END_SRC


The following are the topic-level configurations. The server's default configuration for this property is given under the Server Default Property heading, setting this default in the server config allows you to change the default given to topics that have no override specified.


* cleanup.policy
|Default |delete|
|Server Default Property|log.cleanup.policy|
A string that is either "delete" or "compact". This string designates the retention policy to use on old log segments. The default policy ("delete") will discard old segments when their retention time or size limit has been reached. The "compact" setting will enable log compaction on the topic.
* delete.retention.ms
|Default|86400000 (24 hours)|
|Server Default Property|log.cleaner.delete.retention.ms|
The amount of time to retain delete tombstone markers for log compacted topics. This setting also gives a bound on the time in which a consumer must complete a read if they begin from offset 0 to ensure that they get a valid snapshot of the final stage (otherwise delete tombstones may be collected before they complete their scan).
* flush.messages
|Default|None|
|Server Default Property|log.flush.interval.messages|
This setting allows specifying an interval at which we will force an fsync of data written to the log. For example if this was set to 1 we would fsync after every message; if it were 5 we would fsync after every five messages. In general we recommend you not set this and use replication for durability and allow the operating system's background flush capabilities as it is more efficient. This setting can be overridden on a per-topic basis (see the per-topic configuration section).
* flush.ms
|Default|None|
|Server Default Property|log.flush.interval.ms|
This setting allows specifying a time interval at which we will force an fsync of data written to the log. For example if this was set to 1000 we would fsync after 1000 ms had passed. In general we recommend you not set this and use replication for durability and allow the operating system's background flush capabilities as it is more efficient.
* index.interval.bytes
|Default|4096|
|Server Default Property|log.index.interval.bytes|
This setting controls how frequently Kafka adds an index entry to it's offset index. The default setting ensures that we index a message roughly every 4096 bytes. More indexing allows reads to jump closer to the exact position in the log but makes the index larger. You probably don't need to change this.
* max.message.bytes
|Default|1,000,000|
|Server Default Property|message.max.bytes|
This is largest message size Kafka will allow to be appended to this topic. Note that if you increase this size you must also increase your consumer's fetch size so they can fetch messages this large.
* min.cleanable.dirty.ratio
|Default|0.5|
|Server Default Property|log.cleaner.min.cleanable.ratio|
This configuration controls how frequently the log compactor will attempt to clean the log (assuming log compaction is enabled). By default we will avoid cleaning a log where more than 50% of the log has been compacted. This ratio bounds the maximum space wasted in the log by duplicates (at 50% at most 50% of the log could be duplicates). A higher ratio will mean fewer, more efficient cleanings but will mean more wasted space in the log.
* min.insync.replicas
|Default|1|
|Server Default Property|min.insync.replicas|
When a producer sets request.required.acks to -1, min.insync.replicas specifies the minimum number of replicas that must acknowledge a write for the write to be considered successful. If this minimum cannot be met, then the producer will raise an exception (either NotEnoughReplicas or NotEnoughReplicasAfterAppend).

When used together, min.insync.replicas and request.required.acks allow you to enforce greater durability guarantees. A typical scenario would be to create a topic with a replication factor of 3, set min.insync.replicas to 2, and produce with request.required.acks of -1. This will ensure that the producer raises an exception if a majority of replicas do not receive a write.
* retention.bytes
|Default|None|
|Server Default Property|log.retention.bytes|
This configuration controls the maximum size a log can grow to before we will discard old log segments to free up space if we are using the "delete" retention policy. By default there is no size limit only a time limit.
* retention.ms
|Default|7 days|
|Server Default Property|log.retention.minutes|
This configuration controls the maximum time we will retain a log before we will discard old log segments to free up space if we are using the "delete" retention policy. This represents an SLA on how soon consumers must read their data.
* segment.bytes
|Default|1 GB|
|Server Default Property|log.segment.bytes|
This configuration controls the segment file size for the log. Retention and cleaning is always done a file at a time so a larger segment size means fewer files but less granular control over retention.
* segment.index.bytes
|Default|10 MB|
|Server Default Property|log.index.size.max.bytes|
This configuration controls the size of the index that maps offsets to file positions. We preallocate this index file and shrink it only after log rolls. You generally should not need to change this setting.
* segment.ms
|Default|7 days|
|Server Default Property|log.roll.hours|
This configuration controls the period of time after which Kafka will force the log to roll even if the segment file isn't full to ensure that retention can delete or compact old data.
* segment.jitter.ms
|Default|0|
|Server Default Property|log.roll.jitter.{ms,hours}|
The maximum jitter to subtract from logRollTimeMillis.
